function path = exportDRReport(out,path)
%EXPORTDRREPORT Two-page PDF using the original vector export workflow.
% Images are analysis previews; original full resolution remains at source.
if nargin < 2, path = fullfile(out.outputFolder,'screening_report.pdf'); end
f = figure('Visible','off','Color','white','Position',[100 100 1120 790], ...
    'Name','DR screening report'); cleaner = onCleanup(@() close(f));
annotation(f,'textbox',[.035 .92 .93 .055],'String','RETINAL SCREENING | RESEARCH PROTOTYPE', ...
    'FontSize',18,'FontWeight','bold','EdgeColor','none','Color',[.04 .22 .30]);
annotation(f,'textbox',[.035 .865 .93 .05],'String', ...
    sprintf('Case: %s    |    %s    |    Quality: %s', ...
    out.imageID,out.timestamp,out.quality.status), ...
    'FontSize',11,'Interpreter','none','EdgeColor','none');
reportImage(f,[.035 .53 .44 .32],out.original,'Original (preview)');
reportImage(f,[.52 .53 .44 .32],out.enhanced,'Enhanced / unchanged (preview)');
reportImage(f,[.035 .18 .44 .32],out.evidence.overlay,'Structure and lesion CANDIDATES');
if out.explanation.available
    reportImage(f,[.52 .18 .44 .32],out.explanation.overlay,'Grad-CAM | CNN attention');
else
    ax = axes(f,'Position',[.52 .18 .44 .32]); axis(ax,'off');
    text(ax,.02,.65,'Grad-CAM unavailable','FontSize',15,'FontWeight','bold');
    text(ax,.02,.40,out.explanation.message,'FontSize',10,'Interpreter','none');
end
annotation(f,'textbox',[.035 .08 .93 .07],'String', ...
    'Overlay: cyan vessels | red MA candidates | purple hemorrhage candidates | yellow exudate candidates | green disc estimate | white fovea estimate', ...
    'FontSize',10,'EdgeColor','none','Interpreter','none');
annotation(f,'textbox',[.035 .025 .93 .04],'String', ...
    'NOT A DIAGNOSIS. Unvalidated screening estimate; ophthalmologist confirmation required.', ...
    'FontSize',10,'FontWeight','bold','Color',[.65 .12 .12],'EdgeColor','none');
exportgraphics(f,path,'ContentType','vector','BackgroundColor','white');
clear cleaner
f = figure('Visible','off','Color','white','Position',[100 100 1120 790]);
cleaner = onCleanup(@() close(f));
annotation(f,'textbox',[.04 .91 .92 .07],'String','RESULTS, EVIDENCE AND REVIEW', ...
    'FontSize',18,'FontWeight','bold','EdgeColor','none','Color',[.04 .22 .30]);
if out.prediction.available
    scoreType = 'Uncalibrated model score';
    if out.prediction.calibrated, scoreType = 'Temperature-scaled score'; end
    flag = 'Below configured referral threshold';
    if out.prediction.referableFlag, flag = 'Meets configured referral threshold'; end
    result = sprintf('Model grade: %d / 4\n%s: %.1f%%\nGrade 2+ score: %.1f%% | %s\nClassifier: %s\n%s', ...
        out.prediction.grade,scoreType,100*out.prediction.score, ...
        100*out.prediction.referableScore,flag,out.prediction.method,out.prediction.message);
else
    result = ['Model grade: NOT AVAILABLE' newline out.prediction.message];
end
annotation(f,'textbox',[.04 .68 .92 .21],'String',result, ...
    'FontSize',12,'EdgeColor',[.8 .85 .87],'BackgroundColor',[.96 .98 .99], ...
    'Interpreter','none','Margin',12);
counts = out.evidence.counts;
evidence = sprintf(['Untrained candidates: MA %d | Hemorrhages %d | Exudates %d\n' ...
    'Vessel area fraction: %.3f\nNeovascularization: %s\n' ...
    'Optic disc/fovea: geometric estimates; anatomical coverage is not verified.\n' ...
    'Analysis resolution: %d x %d; native input: %d x %d.'], ...
    counts.MA,counts.HE,counts.EX,out.evidence.features(7), ...
    out.evidence.neovascularization,out.evidence.analysisSize(2), ...
    out.evidence.analysisSize(1),out.evidence.nativeSize(2),out.evidence.nativeSize(1));
annotation(f,'textbox',[.04 .47 .92 .19],'String',evidence,'FontSize',11, ...
    'EdgeColor','none','Interpreter','none');
m = out.quality.before;
quality = sprintf(['Quality: %s | Focus %.6g | Mean intensity %.3f\n' ...
    'Contrast %.3f | Illumination CV %.3f | Noise %.4f\n' ...
    'Operations: %s\nFeedback: %s'],out.quality.status,m.focus,m.mean, ...
    m.contrast,m.illuminationCV,m.noise,strjoin(out.quality.operations,', '),out.quality.message);
annotation(f,'textbox',[.04 .29 .92 .17],'String',quality,'FontSize',10, ...
    'EdgeColor','none','Interpreter','none');
review = sprintf('Review: %s | Reviewer: %s\nDoctor-recorded grade: %s\nNotes: %s', ...
    out.review.status,out.review.reviewer,out.review.confirmedGrade,out.review.notes);
annotation(f,'textbox',[.04 .135 .92 .14],'String',review,'FontSize',11, ...
    'EdgeColor',[.8 .85 .87],'Interpreter','none','Margin',10);
annotation(f,'textbox',[.04 .035 .92 .08],'String', ...
    ['Research demo: no sensitivity/specificity guarantee. Lesion candidates require confirmation. ' ...
    'Grad-CAM explains CNN attention and does not prove clinical correctness. ' ...
    'This report supplies no treatment or prescription.'], ...
    'FontSize',10,'EdgeColor','none','Color',[.65 .12 .12]);
exportgraphics(f,path,'Append',true,'ContentType','vector','BackgroundColor','white');
end

function reportImage(f,position,I,label)
% Use explicit RGB bytes for export; never auto-stretch image contrast.
% Bicubic preview resizing can overshoot [0,1]. Clip for display only.
I = im2single(I);
validateattributes(I,{'single'},{'real','finite','nonempty'});
I = min(single(1),max(single(0),I));
ax = axes(f,'Position',position,'Color','white');
imshow(im2uint8(I),'Parent',ax);
title(ax,label,'FontSize',12,'Interpreter','none','Color',[.1 .1 .1]);
end
