function writeCaseSummary(out)
%WRITECASESUMMARY Compact audit metadata, no network or hidden image arrays.
s = struct('version',out.version,'imageID',out.imageID,'source',out.source, ...
    'timestamp',out.timestamp,'quality',out.quality,'prediction',out.prediction, ...
    'candidateCounts',out.evidence.counts,'evidenceMessage',out.evidence.message, ...
    'neovascularization',out.evidence.neovascularization, ...
    'gradCAMAvailable',out.explanation.available,'gradCAMMessage',out.explanation.message, ...
    'review',out.review,'analysisSecondsExcludingExports',out.seconds,'clinicalReady',false);
fid = fopen(fullfile(out.outputFolder,'case_summary.json'),'w','n','UTF-8');
if fid<0, error('drdemo:Output','Cannot write case summary.'); end
closer = onCleanup(@() fclose(fid)); fprintf(fid,'%s\n',jsonencode(s));
end
